"""empty message

Revision ID: 846a39f1fb35
Revises: 40eeb4194eae
Create Date: 2023-03-05 21:58:04.278396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '846a39f1fb35'
down_revision = '40eeb4194eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
